name: Crear rama con GitHub CLI

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Nombre de la nueva rama'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Clonar el repositorio con GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo clone ${{ github.repository }} repo
          cd repo
          git config user.name "murillowilmar1"
          git config user.email "murillowilmar1@gmail.com"
          git checkout -b ${{ github.event.inputs.branch_name }} origin/main
          git push origin ${{ github.event.inputs.branch_name }}
