name: Crear rama usando GitHub CLI

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Nombre de la nueva rama'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Autenticar GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Crear rama desde main usando GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo clone ${{ github.repository }} repo
          cd repo
          git checkout -b ${{ github.event.inputs.branch_name }} origin/main
          git push origin ${{ github.event.inputs.branch_name }}
