name: Configurar Git en GitHub Actions

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  setup-git:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código fuente
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config --global user.name "murillowilmar1"
          git config --global user.email "murillowilmar1@gmail.com"

      - name: Validar configuración de usuario Git
        run: |
          NAME=$(git config --global --get user.name)
          EMAIL=$(git config --global --get user.email)

          if [[ "$NAME" == "murillowilmar1" && "$EMAIL" == "murillowilmar1@gmail.com" ]]; then
            echo "✅ Configuración correcta de usuario Git: $NAME <$EMAIL>"
          else
            echo "❌ Configuración incorrecta: $NAME <$EMAIL>"
            exit 1
          fi

